// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SakilaProject1.Data;

namespace SakilaProject1.Migrations
{
    [DbContext(typeof(SakilaProject1Context))]
    [Migration("20200810151632_immortal")]
    partial class immortal
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SakilaProject1.Models.Inventory", b =>
                {
                    b.Property<int>("Inventory_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Film_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Last_update")
                        .HasColumnType("datetime2");

                    b.Property<int>("Store_id")
                        .HasColumnType("int");

                    b.HasKey("Inventory_id");

                    b.ToTable("Inventory");
                });

            modelBuilder.Entity("SakilaProject1.Models.Payment", b =>
                {
                    b.Property<int>("Payment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("Customer_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Last_update")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Payment_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Rental_id")
                        .HasColumnType("int");

                    b.Property<byte>("Staff_id")
                        .HasColumnType("tinyint");

                    b.HasKey("Payment_id");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("SakilaProject1.Models.Rental", b =>
                {
                    b.Property<int>("Rental_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Customer_id")
                        .HasColumnType("int");

                    b.Property<int>("Inventory_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Last_update")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Rental_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Return_date")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Staff_id")
                        .HasColumnType("tinyint");

                    b.HasKey("Rental_id");

                    b.ToTable("Rental");
                });
#pragma warning restore 612, 618
        }
    }
}
